### ISSUE TITLE
Replace caps font with small caps font

### ISSUE THREAD

**Issue by nazarov-tech** [spbpython/kdpv_generator#17]
designer comment: это будет смотреться СРАЗУ сильно лучше

(we need to find out if it's true)

**Comment by nazarov-tech** [comment]
@teners maybe you have any ideas of such font? with cyrillic support

**Comment by teners** [comment]
@nazarov-tech since 4.2.0 Pillow's [Draw.text](http://pillow.readthedocs.io/en/4.2.x/reference/ImageDraw.html?highlight=text#PIL.ImageDraw.PIL.ImageDraw.Draw.text) supports `features` parameter, I'll give it a try with "[smcp](https://www.microsoft.com/typography/otspec/features_pt.htm#smcp)" and if it looks good, I'll submit a pull request ;)

**Comment by nazarov-tech** [comment]
done
